### ISSUE TITLE
feat: image generation settings

### ISSUE THREAD

**Issue by alexandreteles** [juztim/FutureDesk-Issues#23]
Although I am certain that the most advanced settings will be hidden away for the foreseeable future, I have some considerations to make about those:

![](https://cdn.upload.systems/uploads/nlbaHzUQ.png)

1. Consider picking a newer and more versatile model as default and allow the user to change it based on the models offered by the platform:

![](https://cdn.upload.systems/uploads/1Cd8iza2.png)

If no model is specified, Prodia will default to a very old version of Stable Diffusion (1.4) which is less than ideal. My suggestions for default models are either [deliberate_v2.safetensors [10ec4b29]](https://civitai.com/models/4823/deliberate) (as a strong first) or [theallys-mix-ii-churned.safetensors [5d9225a4]](https://civitai.com/models/3848/theallys-mix-ii-churned).

2. Include a general negative-prompt:

```text
worst quality, low quality, normal quality, lowres, low resolution, cropped, out of frame, sketch, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, mutated hands and fingers, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, jpeg artifacts, signature, watermark, username, blurry, poorly drawn hands, poorly drawn limbs, bad anatomy, deformed, amateur drawing, odd
```

3. Use DPM++ 2M Karras as the sampler:

![](https://cdn.upload.systems/uploads/Fzp4Vm6u.png)
Euler on the left and DPM **2M Karras on the right. 

4. Generate images in the `portrait` aspect ratio by default to fit the chat aesthetic better (square images are very unusual).

5. Enable upscaling and downscale to show, as the cost for generation is the same, and upscaling results in more usable (and refined) images.

6. Run at 30 steps, as 25 is incredibly low for Euler/Euler A and borderline minimum for Heun/Karras.

7. Save the generation information with the image, especially the seed, in case the user wants to generate a variation of that image.

Here is a good reading: https://blog.openart.ai/2023/02/13/the-most-complete-guide-to-stable-diffusion-parameters/

**Comment by alexandreteles** [comment]
Oh, and I forgot to mention that you *always* want to prepend `masterpiece, best quality` to your prompt.

**Comment by juztim** [comment]
Implemented
